version: '3.1'
services:
  mongo:
    image: 'mongo:3.6'
    ports:
      - '27017:27017'
    volumes:
      - '/data/mongo:/data/db'
  rabbit:
    image: "rabbitmq:3.7-management-alpine"
    ports:
      - "15672:15672"
      - "5672:5672"
